# -*- coding: utf-8 -*-
"""Shipment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zrmQQ810Q0kIOLPuNfkFlGlFmQXltp0
"""

import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
df = pd.read_csv('shipment_data.csv')
print(df.head(10))

df['Shipment_Date'] = pd.to_datetime(df['Shipment_Date'])
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])

df.dropna(inplace=True)

df['Lead_Time'] = (df['Delivery_Date'] - df['Shipment_Date']).dt.days

SLA_DAYS = 7
df['Late_Delivery'] = df['Lead_Time'] > SLA_DAYS
print(df.head(10))

cleaned_df = df[['Supplier', 'Shipment_Date', 'Delivery_Date', 'Lead_Time', 'Late_Delivery']]
cleaned_df.to_csv("cleaned_lead_time_data.csv", index=False)

print("Cleaned dataset saved.", df.head(10))

plt.figure(figsize=(10,6))
sns.histplot(data=df, x='Lead_Time', hue='Supplier', multiple='stack')
plt.title("Lead Time Distribution by Supplier")
plt.xlabel("Lead Time (Days)")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(data=df, x='Supplier', y='Lead_Time')
plt.title("Lead Time by Supplier (Boxplot)")
plt.xlabel("Supplier")
plt.ylabel("Lead Time (Days)")
plt.show()

supplier_summary = df.groupby('Supplier').agg(
    Total_Shipments=('Lead_Time', 'count'),
    Avg_Lead_Time=('Lead_Time', 'mean'),
    Median_Lead_Time=('Lead_Time', 'median'),
    Late_Deliveries=('Late_Delivery', 'sum')
).reset_index()

supplier_summary['On_Time_Rate_%'] = (
    (supplier_summary['Total_Shipments'] - supplier_summary['Late_Deliveries'])
    / supplier_summary['Total_Shipments'] * 100
)

supplier_summary = supplier_summary.sort_values(
    by=['Late_Deliveries', 'Avg_Lead_Time']
)

supplier_summary.to_csv("supplier_performance_summary.csv", index=False)
display(supplier_summary)

best_supplier = supplier_summary.iloc[0]
print("\nRecommended Supplier:")
print(best_supplier['Supplier'])